version: '3.3'

services:

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - log:/log
    ports:
      - 6969:27017

  server:
    container_name: server
    environment:
      - MONGO_CONNSTRING=mongodb://mongo:27017
      - FRONTEND_HOST=http://localhost:3000
      - HOUSES_PER_PAGE=20
      - LOG_LEVEL=3
      - PORT=1337
      - KEY=0e48b1f442ef4de19064663a91317f1c
      - REQUIRE_KEY=1
    volumes:
      - log:/log
    ports:
      - 1337:1337
    build: ./nosql2h22-estate-backend
    depends_on:
      - mongo

  mongo-express:
      container_name: mongo-express
      image: mongo-express
      environment:
        - ME_CONFIG_OPTIONS_EDITORTHEME=monokai
      depends_on:
        - mongo
      ports:
        - 42069:8081
        
  frontend:
    container_name: client
    ports:
      - 3000:3000
    build: ./nosql2h22-estate-frontend

volumes:
  log:
  mongo:
  mongodb-data:

