export const col_names = [
  "Улица",
  "Номер дома",
  "Дробный номер дома",
  "Корпус",
  "Литера",
  "Район",
  "Коммунальные квартиры",
  "Квартиры",
  "Серия, тип проекта",
  "Год постройки",
  "Год проведения реконструкции",
  "Общая площадь здания, м2",
  "Площадь жилых помещений, м2",
  "Площадь нежилых помещ. функц. назначения, м2",
  "Число лестниц",
  "Число этажей",
  "Количество проживающих",
  "Площадь мансард, м2",
  "Центральное отопление",
  "Автономная котельная",
  "Печное отопление",
  "Центральное горячее водоснабжение",
  "Горячее водоснабжение от газ. колонок",
  "Горячее водоснабжение от дров. колонок",
  "Центральное электроснабжение",
  "Центральное газоснабжение",
  "Мусоропроводы",
  "Кол-во встроенных нежилых помещений",
  "Год ввода лифтов в эксплуатацию",
  "Год реконструкции лифтов",
  "Год модернизации лифтов",
  "Общая площадь уборки придомовых территорий, м2",
  "Дата составления ТЭП",
  "Наименование управляющей компании",
  "Аварийность",
  "Год проведения кап. ремонта",
  "Виды работ",
  "Количество стволов мусоропровода",
  "Площадь металлической кровли",
  "Общее количество лифтов",
  "Количество ПЗУ",
  "Площадь подвалов, м2"
]

export const col_names_eng = [
  "street",
  "houseNumber",
  "houseFractionNumber",
  "housing",
  "character",
  "district",
  "commune",
  "flat",
  "series",
  "yearBuild",
  "yearReconstruct",
  "areaHouse",
  "areaLiving",
  "areaFunctional",
  "countLadder",
  "countFloor",
  "countLiving",
  "areaAttic",
  "hasCentralHeating",
  "hasAutonomousBoiler",
  "hasFurnanceHeating",
  "hasCentralHotWater",
  "hasCentralHotWaterGas",
  "hasCentralHotWaterWood",
  "hasCentralElectricity",
  "hasCentralGas",
  "hasChute",
  "functionalCount",
  "yearLiftBuild",
  "yearLiftReconstruct",
  "yearLiftUpgrade",
  "areaCleaning",
  "tapDate",
  "mcName",
  "hasAccident",
  "capitalRepairDates",
  "workTypes",
  "countChute",
  "areaMetalRoof",
  "countLift",
  "countIntercom",
  "areaBasement"
]

export const test_rowdata = [
  {
      street: "cccc",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "aaaa",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "bbbb",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  },
  {
      street: "fds",
      houseNumber: [3,4,1],
      houseFractionNumber: 4,
      housing: 2,
      character: "F",
      district: "'fsd",
      commune: [{roomsCount: 4, count: 2}],
      flat: [{roomsCount: 1, count: 7}],
      series: "fds",
      yearBuild: 1997,
      yearReconstruct: 2000,
      areaHouse: 49.5,
      areaLiving: 50.2,
      areaFunctional: 49.2,
      countLadder: 4,
      countFloor: 2,
      countLiving: 5,
      areaAttic: 32.4,
      hasCentralHeating: true,
      hasAutonomousBoiler: true,
      hasFurnanceHeating: true,
      hasCentralHotWater: true,
      hasCentralHotWaterGas: false,
      hasCentralHotWaterWood: true,
      hasCentralElectricity: true,
      hasCentralGas: true,
      hasChute: false,
      functionalCount: 9,
      yearLiftBuild: 2000,
      yearLiftReconstruct: 2001,
      yearLiftUpgrade: 2002,
      areaCleaning: 19.4,
      tapDate: "gsfd",
      mcName: "fdsds",
      hasAccident: false,
      capitalRepairDates: [1998, 2001],
      workTypes: ["fds", "fdsa", "asdf"],
      countChute: 0,
      areaMetalRoof: 39.2,
      countLift: 2,
      countIntercom: 3,
      areaBasement: 9.3
  }
]