export const scheme = [
  { name: "street", type: "string" },
  { name: "houseNumber", type: "arrayOfInt" },
  { name: "houseFractionNumber", type: "int" },
  { name: "housing", type: "int" },
  { name: "character", type: "string" },
  { name: "district", type: "string" },
  { name: "commune", type: "arrayOfCommune" },
  { name: "commune.count", type: "number", filter: true },
  { name: "commune.roomsCount", type: "number", filter: true },
  { name: "flat", type: "arrayOfFlat" },
  { name: "flat.count", type: "number", filter: true },
  { name: "flat.roomsCount", type: "number", filter: true },
  { name: "series", type: "string" },
  { name: "yearBuild", type: "int" },
  { name: "yearReconstruct", type: "int" },
  { name: "areaHouse", type: "float" },
  { name: "areaLiving", type: "float" },
  { name: "areaFunctional", type: "float" },
  { name: "countLadder", type: "int" },
  { name: "countFloor", type: "int" },
  { name: "countLiving", type: "int" },
  { name: "areaAttic", type: "float" },
  { name: "hasCentralHeating", type: "boolean" },
  { name: "hasAutonomousBoiler", type: "boolean" },
  { name: "hasFurnanceHeating", type: "boolean" },
  { name: "hasCentralHotWater", type: "boolean" },
  { name: "hasCentralHotWaterGas", type: "boolean" },
  { name: "hasCentralHotWaterWood", type: "boolean" },
  { name: "hasCentralElectricity", type: "boolean" },
  { name: "hasCentralGas", type: "boolean" },
  { name: "hasChute", type: "boolean" },
  { name: "functionalCount", type: "int" },
  { name: "yearLiftBuild", type: "int" },
  { name: "yearLiftReconstruct", type: "int" },
  { name: "yearLiftUpgrade", type: "int" },
  { name: "areaCleaning", type: "float" },
  { name: "tapDate", type: "string" },
  { name: "mcName", type: "string" },
  { name: "hasAccident", type: "boolean" },
  { name: "capitalRepairDates", type: "arrayOfInt" },
  { name: "workTypes", type: "arrayOfString" },
  { name: "countChute", type: "int" },
  { name: "areaMetalRoof", type: "float" },
  { name: "countLift", type: "int" },
  { name: "countIntercom", type: "int" },
  { name: "areaBasement", type: "float" },
];
