export const scheme = [
  { name: "street", type: "string" },
  { name: "houseNumber", type: "arrayOfInt" },
  { name: "houseFractionNumber", type: "int" },
  { name: "housing", type: "int", default: null },
  { name: "character", type: "string" },
  { name: "district", type: "string" },
  { name: "commune", type: "arrayOfCommune", default: [] },
  { name: "commune.count", type: "int", filter: true },
  { name: "commune.roomsCount", type: "int", filter: true },
  { name: "flat", type: "arrayOfFlat", default: [] },
  { name: "flat.count", type: "int", filter: true },
  { name: "flat.roomsCount", type: "int", filter: true },
  { name: "series", type: "string", default: null },
  { name: "yearBuild", type: "int" },
  { name: "yearReconstruct", type: "int", default: null },
  { name: "areaHouse", type: "float" },
  { name: "areaLiving", type: "float" },
  { name: "areaFunctional", type: "float", default: 0 },
  { name: "countLadder", type: "int" },
  { name: "countFloor", type: "int" },
  { name: "countLiving", type: "int" },
  { name: "areaAttic", type: "float", default: 0 },
  { name: "hasCentralHeating", type: "boolean" },
  { name: "hasAutonomousBoiler", type: "boolean" },
  { name: "hasFurnanceHeating", type: "boolean" },
  { name: "hasCentralHotWater", type: "boolean" },
  { name: "hasCentralHotWaterGas", type: "boolean" },
  { name: "hasCentralHotWaterWood", type: "boolean" },
  { name: "hasCentralElectricity", type: "boolean" },
  { name: "hasCentralGas", type: "boolean" },
  { name: "hasChute", type: "boolean" },
  { name: "functionalCount", type: "int", default: 0 },
  { name: "yearLiftBuild", type: "int", default: null },
  { name: "yearLiftReconstruct", type: "int", default: null },
  { name: "yearLiftUpgrade", type: "int", default: null },
  { name: "areaCleaning", type: "float", default: 0 },
  { name: "tapDate", type: "string" },
  { name: "mcName", type: "string" },
  { name: "hasAccident", type: "boolean" },
  { name: "capitalRepairDates", type: "arrayOfInt", default: [] },
  { name: "workTypes", type: "arrayOfString", default: [] },
  { name: "countChute", type: "int", default: 0 },
  { name: "areaMetalRoof", type: "float", default: 0 },
  { name: "countLift", type: "int", default: 0 },
  { name: "countIntercom", type: "int", default: 0 },
  { name: "areaBasement", type: "float", default: 0 },
];

export const defaultHouse = scheme.reduce((map, prop) => {
  if (prop.default !== undefined) {
    map[prop.name] = prop.default;
  }

  return map;
}, {});

export const csvHeaders = [
  "street",
  "house",
  "housing",
  "character",
  "district",
  "communeType",
  "communeCount",
  undefined,
  "series",
  "yearBuild",
  "yearReconstruct",
  "areaHouse",
  "areaLiving",
  "areaFunctional",
  "countLadder",
  "countFloor",
  "countLiving",
  "areaAttic",
  "hasCentralHeating",
  "hasAutonomousBoiler",
  "hasFurnanceHeating",
  "hasCentralHotWater",
  "hasCentralHotWaterGas",
  "hasCentralHotWaterWood",
  "hasCentralElectricity",
  "hasCentralGas",
  "hasChute",
  "flatType",
  "flatCount",
  undefined,
  "functionalCount",
  "yearLiftBuild",
  "yearLiftReconstruct",
  "yearLiftUpgrade",
  "areaCleaning",
  "tapDate",
  "mcName",
  "hasAccident",
  "capitalRepairDates",
  "workTypes",
  "countChute",
  "areaMetalRoof",
  "countLift",
  "countIntercom",
  "areaBasement",
];
